server:
  port: 8081

spring:
  application:
    name: api-passenger
  profiles:
    active: prod
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

      config:
        server-addr: localhost:8848
        file-extension: yaml
